export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FETCH_APPOINTMENTS = 'FETCH_APPOINTMENTS';
export const ADD_APPOINTMENT = 'ADD_APPOINTMENT';
export const FETCH_APPOINTMENT_BY_ID = 'FETCH_APPOINTMENT_BY_ID';