// <auto-generated />
using System;
using AppointmentService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppointmentService.Migrations
{
    [DbContext(typeof(AppointmentDbContext))]
    partial class AppointmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AppointmentService.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2024, 12, 25, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dental check-up",
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2024, 12, 27, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Annual physical exam",
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2025, 1, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Regular checkup",
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2025, 1, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Physical exam",
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDate = new DateTime(2025, 2, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Blood Test",
                            IsDeleted = false,
                            UserId = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
